// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';

export function AcceptTransfer(arg1:string):Promise<boolean>;

export function CancelTransfer(arg1:string):Promise<boolean>;

export function DeclineTransfer(arg1:string):Promise<boolean>;

export function GetDeviceName():Promise<string>;

export function GetPeers():Promise<Array<discovery.Peer>>;

export function ResetDiscovery():Promise<void>;

export function SelectAndSendFile(arg1:string):Promise<string>;
