// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1) {
  return window['go']['main']['App']['AcceptTransfer'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function DeclineTransfer(arg1) {
  return window['go']['main']['App']['DeclineTransfer'](arg1);
}

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function ResetDiscovery() {
  return window['go']['main']['App']['ResetDiscovery']();
}

export function SelectAndSendFile(arg1) {
  return window['go']['main']['App']['SelectAndSendFile'](arg1);
}
